export const SUBMENU_MOUSE_ENTER = 'SUBMENU_MOUSE_ENTER'
export const SUBMENU_MOUSE_LEAVE = 'SUBMENU_MOUSE_LEAVE'
export const SET_MOUSE_MOVEIN = "SET_MOUSE_MOVEIN"
export const CHAT_SHOW_HIDE = 'CHAT_SHOW_HIDE'
export const CHAR_SHOW_TALK = 'CHAR_SHOW_TALK'
export const CHAR_WORORDER_LISTENER = 'CHAR_WORORDER_LISTENER'
export const CHAR_PHONE_LISTENER ="CHAR_PHONE_LISTENER"
export const CHAR_PHONE_OVER = "CHAR_PHONE_OVER"


// 跑马灯
// 往数组对象增加消息
export const ADD_MARQUEE_MESSAGE ="ADD_MARQUEE_MESSAGE"
export const DELETE_MARQUEE_MESSAGE = "DELETE_MARQUEE_MESSAGE"
export const HEAR_PHONE_SHOW = "HEAR_PHONE_SHOW"
export const HEAR_PHONE_HIDE = "HEAR_PHONE_HIDE"
export const HEAR_IMCHAT_SHOW = "HEAR_IMCHAT_SHOW"
export const HEAR_IMCHAT_HIDE = "HEAR_IMCHAT_HIDE"
export const HEAR_IMCHAT_HIDETRUE = "HEAR_IMCHAT_HIDETRUE"
export const HEAR_PHONE_SHOWTRUE = "HEAR_PHONE_SHOWTRUE"

//实时转译
export const TRANSFORM_SHOWTRUE = "TRANSFORM_SHOWTRUE"


// IM消息
export const SET_MSG_FROM_IPCC = "SET_MSG_FROM_IPCC"
//IM消息数量
export const IMCHAT_MSG_NUM = "IMCHAT_MSG_NUM"
//im的消息重量
export const IMCAHT_MSG_CONTENT = "IMCAHT_MSG_CONTENT"
//座席聊天监听座席的状态
export const AGENT_CHAT_STATUS = "AGENT_CHAT_STATUS"
//座席聊天弹框页面的监听
export const AGENT_CHATPOP_SHOWHIDE = "AGENT_CHATPOP_SHOWHIDE"
export const AGENT_CHATPOP_NAME = "AGENT_CHATPOP_NAME"
export const AGENT_CHAT_INFO = "AGENT_CHAT_INFO"
export const ACCEPT_AGENT_CHAT = "ACCEPT_AGENT_CHAT"//接收从平台发过来的消息
//监听路由跳转
export const ROUTER_ALL_ROAD = " ROUTER_ALL_ROAD"
//监听删除项
export const ROUTER_DELETE_ROAD ="ROUTER_DELETE_ROAD"
//监听消除组件
export const IS_REMOVE_VUEFLAG = "IS_REMOVE_VUEFLAG"
//不消除组件
export const IS_REMOVE_VUEF = "IS_REMOVE_VUETRUE"
//当前路由
export const CURRENT_ROUTE_POS = "CURRENT_ROUTE_POS"

